apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "host-mutator.fullname" . }}
  labels:
    {{- include "host-mutator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "host-mutator.fullname" . }}
subjects:
- kind: ServiceAccount
  {{- if .Values.serviceAccount.create }}
  name: {{ include "host-mutator.serviceAccountName" . }}
  {{- else }}
  name: default
  {{- end }}
  namespace: {{ .Release.Namespace }}
