apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: host-mutator
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - get
  - update
